function Hgt = Hgt(Q_t,Kh_t,D_t,R_t,Q_tp1,Kh_tp1,D_tp1,R_tp1,Qs)
%HGT
%    HGT = HGT(Q_T,KH_T,D_T,R_T,Q_TP1,KH_TP1,D_TP1,R_TP1,QS)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    16-Dec-2015 20:16:07

t2 = Kh_t.*Q_t;
t3 = D_t-Q_t+t2;
t4 = 1.0./t3;
t5 = Q_t-t2;
t6 = t4.*t5;
t7 = t6+1.0;
t8 = R_t.*t7;
t9 = 1.0./Q_t;
t10 = Q_tp1+1.26e-2;
t11 = t8-t4.*t5.*t9.*t10;
t12 = Kh_tp1.*Q_tp1;
Hgt = [t11.*((Q_tp1.*1.8373e-1-Kh_tp1.*Q_tp1.*1.8373e-1)./(D_tp1-Q_tp1+t12)-1.0./2.0e1).*(-5.118924508790072)+t4.*(Q_t-Kh_t.*Q_t);D_tp1-Q_tp1+t12-t3.*t11.*(1.9e1./2.0e1)+1.148e-4;(R_t.*(D_t.*(1.0./1.9e1)-Q_t.*(1.0./1.9e1)-Kh_t.^2.*3.985e-3+Kh_t.*Q_t.*(1.0./1.9e1)+5.772084210526315e-2).*(9.9e1./1.0e2))./(D_tp1.*(1.0./1.9e1)-Q_tp1.*(1.0./1.9e1)-Kh_tp1.^2.*3.985e-3+Kh_tp1.*Q_tp1.*(1.0./1.9e1)+5.772084210526315e-2)-1.0];
