function kHs = KhFsGt2Lt1(Nt,PhIt,Pt,Qrun,Qt,Rt,cHt,kHt)
%KHFSGT2LT1
%    KHS = KHFSGT2LT1(NT,PHIT,PT,QRUN,QT,RT,CHT,KHT)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    22-Dec-2015 13:23:25

t2 = Nt.^2;
t3 = PhIt.^2;
t4 = sqrt(2.0);
t5 = 3.031300775527986e7;
t6 = 1.0./sqrt(Qt);
t7 = Nt.*PhIt.*3.018256175268364e19;
t8 = Pt.*cHt.*kHt.*7.022237718977446e18;
t9 = Pt.*Qrun.*cHt.*kHt.*5.573204538870989e20;
t10 = Nt.*-3.018256175268364e19+t7+t8+t9-Pt.*cHt.*7.022237718977446e18-Pt.*Qrun.*cHt.*5.573204538870989e20;
t11 = 1.0./sqrt(t10);
t12 = Nt.*PhIt.*Qt.*3.138076925420012e35;
t13 = Qt.*Rt.*t2.*2.718603477249461e35;
t14 = PhIt.*Rt.*kHt.*t2.*2.16672697136782e33;
t15 = Nt.*Qt.*Rt.*cHt.*5.382834884953932e36;
t16 = Pt.*Qt.*cHt.*kHt.*7.301011203523124e34;
t17 = Pt.*Qrun.*Qt.*cHt.*kHt.*5.794453336129463e36;
t18 = Pt.*Rt.*cHt.*t2.*t3.*6.325069434898773e34;
t19 = Pt.*Qrun.*Rt.*cHt.*t2.*t3.*5.019896376903788e36;
t20 = Nt.*PhIt.*Pt.*Qt.*Rt.*cHt.*5.319584190604944e36;
t21 = Nt.*Pt.*Qrun.*Qt.*Rt.*cHt.*5.019896376903788e36;
t22 = Nt.*PhIt.*Pt.*Qt.*Rt.*cHt.*kHt.*6.325069434898773e34;
t23 = Nt.*PhIt.*Pt.*Qrun.*Qt.*Rt.*cHt.*kHt.*5.019896376903788e36;
t24 = t12+t13+t14+t15+t16+t17+t18+t19+t20+t21+t22+t23-Nt.*Qt.*3.138076925420012e35-Pt.*Qt.*cHt.*7.301011203523124e34-Rt.*kHt.*t2.*t3.*2.16672697136782e33-Pt.*Qrun.*Qt.*cHt.*5.794453336129463e36-PhIt.*Qt.*Rt.*t2.*2.718603477249461e35-Nt.*PhIt.*Qt.*Rt.*cHt.*5.382834884953932e36-Nt.*Pt.*Qt.*Rt.*cHt.*5.319584190604944e36-PhIt.*Pt.*Rt.*cHt.*t2.*6.325069434898773e34-Nt.*Pt.*Qt.*Rt.*cHt.*kHt.*6.325069434898773e34-PhIt.*Pt.*Qrun.*Rt.*cHt.*t2.*5.019896376903788e36-Nt.*PhIt.*Pt.*Qrun.*Qt.*Rt.*cHt.*5.019896376903788e36-Nt.*Pt.*Qrun.*Qt.*Rt.*cHt.*kHt.*5.019896376903788e36;
t25 = sqrt(t24);
kHs = [t4.*t5.*t6.*t11.*t25.*(-8.706265876922495e-16);t4.*t5.*t6.*t11.*t25.*8.706265876922495e-16];
