function [Ps,Rs,Ds] = OvFsGt2Lt1
%OVFSGT2LT1
%    [PS,RS,DS] = OVFSGT2LT1

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    22-Dec-2015 13:23:26

Ps = zeros(0,1);
if nargout > 1
    Rs = zeros(0,1);
end
if nargout > 2
    Ds = zeros(0,1);
end
