function Hgt = HssGt(in1)
%HSSGT
%    HGT = HSSGT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    23-Dec-2015 20:55:05

D = in1(:,3);
Kh = in1(:,2);
Q = in1(:,1);
R = in1(:,4);
t2 = Kh.*Q;
t3 = D-Q+t2;
t4 = 1.0./t3;
t5 = Q-t2;
t6 = t4.*t5;
t7 = t6+1.0;
t8 = R.*t7;
t9 = 1.0./Q;
t10 = Q+1.26e-2;
t11 = t8-t4.*t5.*t9.*t10;
Hgt = [t11.*(t4.*t5.*1.8373e-1-1.0./2.0e1).*(-5.118924508790072)+t4.*(Q-Kh.*Q),D-Q+t2-t3.*t11.*(1.9e1./2.0e1)+1.1487e-4,R.*(9.9e1./1.0e2)-1.0,Kh.*(-7.97e-3)-Q.*(1.0./1.0e2)+1.2474e-2];
