function Kk = KkEq2Gt1(Dtp1,Qtp1,kHt,kHtp1)
%KKEQ2GT1
%    KK = KKEQ2GT1(DTP1,QTP1,KHT,KHTP1)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    27-Dec-2015 09:03:13

Kk = ((kHt.^2.*3.985e-3-5.7818253e-2).*(Qtp1+1.26e-2).*(-9.9e1./1.0e2))./((kHt.*7.97e-3+((Dtp1.*5.0e3-Qtp1.*2.3373e4+Qtp1.*kHtp1.*2.3373e4).*(Dtp1.*2.305843009213694e18-Qtp1.*2.305843009213694e18+Qtp1.*kHtp1.*2.305843009213694e18+2.64872186468377e14).*2.336820662408206e-23)./((kHt-1.0).*(Dtp1-Qtp1+Qtp1.*kHtp1))).*(Dtp1.*(1.0./1.9e1)-Qtp1.*(1.0./1.9e1)+Qtp1.*kHtp1.*(1.0./1.9e1)-kHtp1.^2.*3.985e-3+5.772091578947369e-2))-1.0;
